# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designprofiles', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designprofile',
            name='interest',
            field=models.ManyToManyField(blank=True, to='project.Catagory'),
        ),
    ]
